### ISSUE TITLE
ModuleNotFoundError: No module named '_bz2'

### ISSUE THREAD

**Issue by mikeitexpert** [alexlaurence/NIfTI-Image-Converter#4]
I am using python 3.7 using the following packages in python virtual environment 

Package    Version
---------- -------
nibabel    2.4.1  
numpy      1.16.4 
pip        19.1.1 
scipy      1.3.0  
setuptools 40.8.0 
six        1.12.0 

But, I get the bellow error :

```
$ python nii2png.py -i /home/mike/Downloads/dgan/0001.nii -o test.png
Traceback (most recent call last):
  File "nii2png.py", line 14, in <module>
    import scipy, numpy, shutil, os, nibabel
  File "/home/mike/Downloads/dgan/venv37/lib/python3.7/site-packages/nibabel/__init__.py", line 51, in <module>
    from . import analyze as ana
  File "/home/mike/Downloads/dgan/venv37/lib/python3.7/site-packages/nibabel/analyze.py", line 87, in <module>
    from .volumeutils import (native_code, swapped_code, make_dt_codes,
  File "/home/mike/Downloads/dgan/venv37/lib/python3.7/site-packages/nibabel/volumeutils.py", line 23, in <module>
    from .openers import Opener, BZ2File
  File "/home/mike/Downloads/dgan/venv37/lib/python3.7/site-packages/nibabel/openers.py", line 16, in <module>
    from bz2 import BZ2File
  File "/usr/local/lib/python3.7/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
```

**Comment by ousswaw** [comment]
i have the same issue ! no one on earth can help us :'(

**Comment by alexlaurence** [comment]
Hi, sorry for the late reply. Did you manage this? Try using Python 3.5 or a lower version, sometimes some packages have not been updated for the latest version of Python...

**Comment by Aliktk** [comment]
can someone guide me that how to use this repo on spyder or jupiter please guid
