### ISSUE TITLE
nibabel.filebasedimages.ImageFileError: Cannot work out file type of 

### ISSUE THREAD

**Issue by StudentRepresentative** [alexlaurence/NIfTI-Image-Converter#8]
Why i got this error?
----------------------------------------------------------
Traceback (most recent call last):
  File "nii2png.py", line 157, in <module>
    main(sys.argv[1:])
  File "nii2png.py", line 38, in main
    image_array = nibabel.load(inputfile).get_data()
  File "C:\Users\rit\Anaconda3\lib\site-packages\nibabel\loadsave.py", line 56, in load
    filename)
nibabel.filebasedimages.ImageFileError: Cannot work out file type of

**Comment by alexlaurence** [comment]
Hi, could you let me know what path you are inputting in? 

https://github.com/nipy/nibabel/issues/620
